namespace SqlQueryGenerator.Core.Heuristics.Goals.Aggregates;

/// <summary>
/// Describes the aggregate function detected inside a selected expression.
/// </summary>
public enum AggregateFunction
{
    /// <summary>
    /// Indicates that no aggregate function was detected.
    /// </summary>
    None = 0,

    /// <summary>
    /// Counts rows or non-null values with COUNT.
    /// </summary>
    Count = 1,

    /// <summary>
    /// Counts unique values with COUNT DISTINCT.
    /// </summary>
    CountDistinct = 2,

    /// <summary>
    /// Sums numeric values with SUM.
    /// </summary>
    Sum = 3,

    /// <summary>
    /// Computes an average value with AVG.
    /// </summary>
    Average = 4,

    /// <summary>
    /// Computes the minimum value with MIN.
    /// </summary>
    Minimum = 5,

    /// <summary>
    /// Computes the maximum value with MAX.
    /// </summary>
    Maximum = 6,

    /// <summary>
    /// Computes a median value through a database-specific expression.
    /// </summary>
    Median = 7,

    /// <summary>
    /// Computes a standard deviation through a database-specific expression.
    /// </summary>
    StandardDeviation = 8,

    /// <summary>
    /// Computes a variance through a database-specific expression.
    /// </summary>
    Variance = 9,

    /// <summary>
    /// Represents a supported but non-standard or user-defined aggregate.
    /// </summary>
    Custom = 99
}

/// <summary>
/// Describes the main human-readable goal inferred for a query containing aggregates.
/// </summary>
public enum AggregateGoalKind
{
    /// <summary>
    /// No aggregate-specific purpose could be inferred.
    /// </summary>
    None = 0,

    /// <summary>
    /// The query mainly counts rows or entities.
    /// </summary>
    RowCount = 1,

    /// <summary>
    /// The query mainly counts unique values.
    /// </summary>
    DistinctCount = 2,

    /// <summary>
    /// The query mainly computes totals.
    /// </summary>
    MetricTotal = 3,

    /// <summary>
    /// The query mainly computes averages.
    /// </summary>
    MetricAverage = 4,

    /// <summary>
    /// The query mainly computes minimums, maximums, or ranges.
    /// </summary>
    MetricExtremes = 5,

    /// <summary>
    /// The query mainly distributes values by one or more dimensions.
    /// </summary>
    Distribution = 6,

    /// <summary>
    /// The query mainly ranks groups or entities by an aggregate metric.
    /// </summary>
    Ranking = 7,

    /// <summary>
    /// The query mainly tracks an aggregate over time.
    /// </summary>
    TimeSeries = 8,

    /// <summary>
    /// The query builds a compact dashboard-like summary with several metrics.
    /// </summary>
    DashboardSummary = 9,

    /// <summary>
    /// The query computes a filtered KPI without grouping.
    /// </summary>
    FilteredKpi = 10,

    /// <summary>
    /// The query looks like a data-quality or completeness check.
    /// </summary>
    DataQuality = 11,

    /// <summary>
    /// The query mixes several aggregate intentions without one dominant pattern.
    /// </summary>
    MixedAggregateSummary = 12
}

/// <summary>
/// Describes the confidence bucket attached to a goal result.
/// </summary>
public enum GoalConfidenceLevel
{
    /// <summary>
    /// The engine has too little signal to be confident.
    /// </summary>
    Low = 0,

    /// <summary>
    /// The engine found useful signals, but the purpose remains partly ambiguous.
    /// </summary>
    Medium = 1,

    /// <summary>
    /// The engine found strong and coherent signals.
    /// </summary>
    High = 2
}

/// <summary>
/// Represents one selected aggregate expression in the query builder.
/// </summary>
public sealed record AggregateProjection
{
    /// <summary>
    /// Initializes a new aggregate projection.
    /// </summary>
    /// <param name="expressionSql">The SQL fragment of the selected aggregate expression.</param>
    /// <param name="function">The aggregate function detected by the builder or parser.</param>
    public AggregateProjection(string expressionSql, AggregateFunction function)
    {
        ExpressionSql = expressionSql ?? string.Empty;
        Function = function;
        ArgumentColumns = Array.Empty<string>();
    }

    /// <summary>
    /// Gets the raw SQL expression selected by the user or generated by the query builder.
    /// </summary>
    public string ExpressionSql { get; init; }

    /// <summary>
    /// Gets the aggregate function represented by <see cref="ExpressionSql"/>.
    /// </summary>
    public AggregateFunction Function { get; init; }

    /// <summary>
    /// Gets the generated or user-defined alias of the aggregate column.
    /// </summary>
    public string? Alias { get; init; }

    /// <summary>
    /// Gets the source table name when the aggregate argument comes from a known table.
    /// </summary>
    public string? SourceTable { get; init; }

    /// <summary>
    /// Gets the source column name when the aggregate argument comes from a known column.
    /// </summary>
    public string? SourceColumn { get; init; }

    /// <summary>
    /// Gets the display name to use in natural-language explanations.
    /// </summary>
    public string? DisplayName { get; init; }

    /// <summary>
    /// Gets the source column comment, when the schema parser loaded comments.
    /// </summary>
    public string? SourceColumnComment { get; init; }

    /// <summary>
    /// Gets whether the aggregate expression uses DISTINCT.
    /// </summary>
    public bool IsDistinct { get; init; }

    /// <summary>
    /// Gets the list of known argument columns referenced by the aggregate expression.
    /// </summary>
    public IReadOnlyList<string> ArgumentColumns { get; init; }

    /// <summary>
    /// Gets whether this aggregate computes a numeric measure rather than a pure count.
    /// </summary>
    public bool IsMeasureAggregate => Function is AggregateFunction.Sum or AggregateFunction.Average or AggregateFunction.Minimum or AggregateFunction.Maximum or AggregateFunction.Median or AggregateFunction.StandardDeviation or AggregateFunction.Variance;
}

/// <summary>
/// Represents one GROUP BY expression or logical grouping dimension.
/// </summary>
public sealed record GroupingProjection
{
    /// <summary>
    /// Initializes a new grouping projection.
    /// </summary>
    /// <param name="expressionSql">The SQL fragment of the grouping expression.</param>
    public GroupingProjection(string expressionSql)
    {
        ExpressionSql = expressionSql ?? string.Empty;
    }

    /// <summary>
    /// Gets the raw SQL expression used in GROUP BY.
    /// </summary>
    public string ExpressionSql { get; init; }

    /// <summary>
    /// Gets the source table name when the grouping expression is bound to a known table.
    /// </summary>
    public string? SourceTable { get; init; }

    /// <summary>
    /// Gets the source column name when the grouping expression is bound to a known column.
    /// </summary>
    public string? SourceColumn { get; init; }

    /// <summary>
    /// Gets the display name to use in explanations.
    /// </summary>
    public string? DisplayName { get; init; }

    /// <summary>
    /// Gets the column comment loaded from schema metadata.
    /// </summary>
    public string? SourceColumnComment { get; init; }

    /// <summary>
    /// Gets whether the grouping expression is derived from a date or time expression.
    /// </summary>
    public bool? IsTemporalOverride { get; init; }

    /// <summary>
    /// Gets whether the grouping column looks like an identifier or foreign key.
    /// </summary>
    public bool? IsIdentifierOverride { get; init; }
}

/// <summary>
/// Represents a WHERE filter, used to explain filtered aggregate KPIs.
/// </summary>
public sealed record FilterCondition
{
    /// <summary>
    /// Initializes a new filter condition.
    /// </summary>
    /// <param name="expressionSql">The SQL fragment of the filter condition.</param>
    public FilterCondition(string expressionSql)
    {
        ExpressionSql = expressionSql ?? string.Empty;
    }

    /// <summary>
    /// Gets the raw SQL expression of the filter.
    /// </summary>
    public string ExpressionSql { get; init; }

    /// <summary>
    /// Gets a human-readable display label for the filtered column or expression.
    /// </summary>
    public string? DisplayName { get; init; }
}

/// <summary>
/// Represents a HAVING condition, used to explain post-aggregation filtering.
/// </summary>
public sealed record HavingCondition
{
    /// <summary>
    /// Initializes a new HAVING condition.
    /// </summary>
    /// <param name="expressionSql">The SQL fragment of the HAVING condition.</param>
    public HavingCondition(string expressionSql)
    {
        ExpressionSql = expressionSql ?? string.Empty;
    }

    /// <summary>
    /// Gets the raw SQL expression of the HAVING predicate.
    /// </summary>
    public string ExpressionSql { get; init; }

    /// <summary>
    /// Gets a human-readable display label for the HAVING predicate.
    /// </summary>
    public string? DisplayName { get; init; }
}

/// <summary>
/// Represents an ORDER BY expression, especially when an aggregate drives a ranking.
/// </summary>
public sealed record OrderProjection
{
    /// <summary>
    /// Initializes a new ordering projection.
    /// </summary>
    /// <param name="expressionSql">The SQL fragment of the ORDER BY expression.</param>
    public OrderProjection(string expressionSql)
    {
        ExpressionSql = expressionSql ?? string.Empty;
    }

    /// <summary>
    /// Gets the raw SQL expression used for ordering.
    /// </summary>
    public string ExpressionSql { get; init; }

    /// <summary>
    /// Gets whether the expression orders by an aggregate value.
    /// </summary>
    public bool IsAggregateOrder { get; init; }

    /// <summary>
    /// Gets whether the order is descending.
    /// </summary>
    public bool IsDescending { get; init; }

    /// <summary>
    /// Gets the display name to use for the ordering expression.
    /// </summary>
    public string? DisplayName { get; init; }
}

/// <summary>
/// Represents minimal index metadata used by the goal heuristic to flag risky aggregate plans.
/// </summary>
public sealed record IndexCoverageSummary
{
    /// <summary>
    /// Initializes a new index coverage summary.
    /// </summary>
    /// <param name="tableName">The table owning the indexed or non-indexed column.</param>
    /// <param name="columnName">The column checked by the index analyzer.</param>
    public IndexCoverageSummary(string tableName, string columnName)
    {
        TableName = tableName ?? string.Empty;
        ColumnName = columnName ?? string.Empty;
    }

    /// <summary>
    /// Gets the table name owning the column.
    /// </summary>
    public string TableName { get; init; }

    /// <summary>
    /// Gets the column name covered or not covered by an index.
    /// </summary>
    public string ColumnName { get; init; }

    /// <summary>
    /// Gets whether the column is covered by at least one known index.
    /// </summary>
    public bool IsIndexed { get; init; }

    /// <summary>
    /// Gets whether the column is the leading column of an index.
    /// </summary>
    public bool IsLeadingColumn { get; init; }

    /// <summary>
    /// Gets the name of the best matching index, when known.
    /// </summary>
    public string? BestIndexName { get; init; }
}

/// <summary>
/// Represents one table participating in the aggregate query.
/// </summary>
public sealed record TableUsageSummary
{
    /// <summary>
    /// Initializes a new table usage summary.
    /// </summary>
    /// <param name="tableName">The physical or logical table name.</param>
    public TableUsageSummary(string tableName)
    {
        TableName = tableName ?? string.Empty;
    }

    /// <summary>
    /// Gets the physical or logical table name.
    /// </summary>
    public string TableName { get; init; }

    /// <summary>
    /// Gets the alias used for this table in SQL.
    /// </summary>
    public string? Alias { get; init; }

    /// <summary>
    /// Gets the user-facing display name for this table.
    /// </summary>
    public string? DisplayName { get; init; }

    /// <summary>
    /// Gets the table comment loaded from schema metadata.
    /// </summary>
    public string? TableComment { get; init; }

    /// <summary>
    /// Gets whether this table is considered the root or fact table of the query.
    /// </summary>
    public bool IsRootTable { get; init; }
}

/// <summary>
/// Contains the minimal query state required by the aggregate goal heuristic.
/// </summary>
public sealed record AggregateQuerySnapshot
{
    /// <summary>
    /// Gets an empty immutable query snapshot.
    /// </summary>
    public static AggregateQuerySnapshot Empty { get; } = new();

    /// <summary>
    /// Gets the tables used by the query.
    /// </summary>
    public IReadOnlyList<TableUsageSummary> Tables { get; init; } = Array.Empty<TableUsageSummary>();

    /// <summary>
    /// Gets aggregate projections selected by the query.
    /// </summary>
    public IReadOnlyList<AggregateProjection> Aggregates { get; init; } = Array.Empty<AggregateProjection>();

    /// <summary>
    /// Gets grouping dimensions used by the query.
    /// </summary>
    public IReadOnlyList<GroupingProjection> Groupings { get; init; } = Array.Empty<GroupingProjection>();

    /// <summary>
    /// Gets filters applied before aggregation.
    /// </summary>
    public IReadOnlyList<FilterCondition> Filters { get; init; } = Array.Empty<FilterCondition>();

    /// <summary>
    /// Gets filters applied after aggregation.
    /// </summary>
    public IReadOnlyList<HavingCondition> HavingConditions { get; init; } = Array.Empty<HavingCondition>();

    /// <summary>
    /// Gets ordering expressions applied to the query.
    /// </summary>
    public IReadOnlyList<OrderProjection> Orderings { get; init; } = Array.Empty<OrderProjection>();

    /// <summary>
    /// Gets index coverage facts computed by the existing index analyzer.
    /// </summary>
    public IReadOnlyList<IndexCoverageSummary> IndexCoverage { get; init; } = Array.Empty<IndexCoverageSummary>();

    /// <summary>
    /// Gets the SQL limit, fetch first, or top value when the query has one.
    /// </summary>
    public int? Limit { get; init; }

    /// <summary>
    /// Gets the generated SQL text when available.
    /// </summary>
    public string? GeneratedSql { get; init; }

    /// <summary>
    /// Gets whether the query builder detected that the user explicitly wants table.*.
    /// </summary>
    public bool HasStarProjection { get; init; }
}

/// <summary>
/// Describes a metric inferred from one aggregate projection.
/// </summary>
public sealed record AggregateMetricIntent
{
    /// <summary>
    /// Initializes a new aggregate metric intent.
    /// </summary>
    /// <param name="function">The aggregate function behind the metric.</param>
    /// <param name="label">The metric label displayed to the user.</param>
    public AggregateMetricIntent(AggregateFunction function, string label)
    {
        Function = function;
        Label = label ?? string.Empty;
    }

    /// <summary>
    /// Gets the aggregate function behind the metric.
    /// </summary>
    public AggregateFunction Function { get; init; }

    /// <summary>
    /// Gets the metric label displayed to the user.
    /// </summary>
    public string Label { get; init; }

    /// <summary>
    /// Gets the original SQL expression behind the metric.
    /// </summary>
    public string? ExpressionSql { get; init; }
}

/// <summary>
/// Describes a grouping dimension inferred from one GROUP BY projection.
/// </summary>
public sealed record GroupingIntent
{
    /// <summary>
    /// Initializes a new grouping intent.
    /// </summary>
    /// <param name="label">The grouping label displayed to the user.</param>
    public GroupingIntent(string label)
    {
        Label = label ?? string.Empty;
    }

    /// <summary>
    /// Gets the grouping label displayed to the user.
    /// </summary>
    public string Label { get; init; }

    /// <summary>
    /// Gets whether the grouping dimension is temporal.
    /// </summary>
    public bool IsTemporal { get; init; }

    /// <summary>
    /// Gets whether the grouping dimension looks like a technical identifier.
    /// </summary>
    public bool IsIdentifier { get; init; }
}

/// <summary>
/// Explains one signal that contributed to the aggregate goal inference.
/// </summary>
public sealed record AggregateGoalReason
{
    /// <summary>
    /// Initializes a new goal reason.
    /// </summary>
    /// <param name="code">A stable machine-readable reason code.</param>
    /// <param name="message">A user-facing reason message.</param>
    /// <param name="weight">The confidence weight contributed by the reason.</param>
    public AggregateGoalReason(string code, string message, double weight)
    {
        Code = code ?? string.Empty;
        Message = message ?? string.Empty;
        Weight = weight;
    }

    /// <summary>
    /// Gets the stable machine-readable reason code.
    /// </summary>
    public string Code { get; init; }

    /// <summary>
    /// Gets the user-facing reason message.
    /// </summary>
    public string Message { get; init; }

    /// <summary>
    /// Gets the confidence weight contributed by the reason.
    /// </summary>
    public double Weight { get; init; }
}

/// <summary>
/// Represents the complete output of the aggregate goal heuristic.
/// </summary>
public sealed record AggregateGoalHeuristicResult
{
    /// <summary>
    /// Gets an empty result used when no aggregate-specific purpose exists.
    /// </summary>
    public static AggregateGoalHeuristicResult Empty { get; } = new()
    {
        Kind = AggregateGoalKind.None,
        Title = "Aucun agrégat détecté",
        Summary = "La requête ne contient pas assez d'agrégats pour déterminer un but statistique.",
        Confidence = 0,
        ConfidenceLevel = GoalConfidenceLevel.Low
    };

    /// <summary>
    /// Gets the inferred aggregate goal kind.
    /// </summary>
    public AggregateGoalKind Kind { get; init; }

    /// <summary>
    /// Gets the short title shown in the UI.
    /// </summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>
    /// Gets the longer natural-language explanation shown in the UI.
    /// </summary>
    public string Summary { get; init; } = string.Empty;

    /// <summary>
    /// Gets the confidence score between 0 and 1.
    /// </summary>
    public double Confidence { get; init; }

    /// <summary>
    /// Gets the confidence bucket derived from <see cref="Confidence"/>.
    /// </summary>
    public GoalConfidenceLevel ConfidenceLevel { get; init; }

    /// <summary>
    /// Gets the metrics detected in the aggregate query.
    /// </summary>
    public IReadOnlyList<AggregateMetricIntent> Metrics { get; init; } = Array.Empty<AggregateMetricIntent>();

    /// <summary>
    /// Gets the grouping dimensions detected in the aggregate query.
    /// </summary>
    public IReadOnlyList<GroupingIntent> Groupings { get; init; } = Array.Empty<GroupingIntent>();

    /// <summary>
    /// Gets the ordered reasons explaining the inference.
    /// </summary>
    public IReadOnlyList<AggregateGoalReason> Reasons { get; init; } = Array.Empty<AggregateGoalReason>();

    /// <summary>
    /// Gets non-blocking warnings to show near the goal explanation.
    /// </summary>
    public IReadOnlyList<string> Warnings { get; init; } = Array.Empty<string>();

    /// <summary>
    /// Gets a suggested user-facing phrase that can be displayed as the interpreted request.
    /// </summary>
    public string? SuggestedUserPhrase { get; init; }

    /// <summary>
    /// Gets whether the result is considered useful enough to replace a generic goal explanation.
    /// </summary>
    public bool IsUseful => Kind != AggregateGoalKind.None && Confidence >= 0.35;
}
