name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-test:
    name: Build and test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore .\SqlQueryGenerator.sln

      - name: Build
        run: dotnet build .\SqlQueryGenerator.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test .\SqlQueryGenerator.sln --configuration Release --no-build --verbosity normal
